<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-ICSBMB7" failures="1" tests="3" name="Personal Loan" time="0.098" errors="0" timestamp="2021-01-27T02:21:56 IST">
  <testcase classname="testcases.Personal_Loan" name="TC_1" time="0.014"/>
  <testcase classname="testcases.Personal_Loan" name="TC_2" time="0.008">
    <failure type="java.lang.AssertionError" message="Intentionally failing the test case">
      <![CDATA[java.lang.AssertionError: Intentionally failing the test case
at testcases.Personal_Loan.TC_2(Personal_Loan.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- TC_2 -->
  <testcase classname="testcases.Personal_Loan" name="TC_3" time="0.003">
    <skipped/>
  </testcase> <!-- TC_3 -->
</testsuite> <!-- Personal Loan -->
